/**:
    ros__parameters:
        image_transport: compressed    # image format
        family: 36h11           # tag family name
        size: 0.19             # tag edge size in meter
        max_hamming: 0          # maximum allowed hamming distance (corrected bits)

    
