image_width: 640
image_height: 480
camera_name: test_camera
distortion_model: equidistant
camera_matrix:
  rows: 3
  cols: 3
  data: [573.26, 0.0, 389.47,
         0.0, 564.92, 240.04,
         0.0, 0.0, 1.0]
distortion_coefficients:
  rows: 1
  cols: 4
  data: [-0.098, 0.388, -0.768, 0.656]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1.0, 0.0, 0.0,
         0.0, 1.0, 0.0,
         0.0, 0.0, 1.0]
projection_matrix:
  rows: 3
  cols: 4
  data: [573.26, 0.0, 389.47, 0.0,
         0.0, 564.92, 240.04, 0.0,
         0.0, 0.0, 1.0, 0.0]


